### ISSUE TITLE
receive address bug

### ISSUE THREAD

**Issue by michael202020** [magnetwork/mag#9]
Hello.
I  am using v1.0.0.0-89c5789 (64-bit).
Here's the problem and how to reproduce it: 
1. Create new wallet
2. Go to receive tab, do not click any buttons.
3. Take address from the "Address" field:
![screenshot from 2019-02-15 13 55 58](https://user-images.githubusercontent.com/47661941/52852458-b6b13e00-3129-11e9-94b2-1ef043fdc6e3.png) and (optionally) send MAG to it.
4. The problem is: THERE IS NO PRIVATE KEY for this address in wallet. Go to Tools->debug console do dumpprivkey GMiHLETQFMgPDxCrEovgJGhpHXZojdXQSg and get 
> Private key for address GMiHLETQFMgPDxCrEovgJGhpHXZojdXQSg is not known (code -4)
5. This address is also not present in dumpwallet dump.
6. Deleting wallet.dat and re-runnning MAG core gives SAME ADDRESS GMiHLETQFMgPDxCrEovgJGhpHXZojdXQSg (while dumppwallet dump is different as it should be).

**Comment by FredericRezeau** [comment]
Fixed here by Roland: https://github.com/magnetwork/mag/commit/9056d8c4a6a0d32cee48fa05325adf4154f46932
